### ISSUE TITLE
jsPDF generation for Ballots

### ISSUE THREAD

**Issue by nikhilsaraf** [NickCarneiro/Debate-Tab#15]
This is the standard for TFA. One needs to be able to pass params for the fields and get a pdf file as an output that can be printed.

http://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=3&sqi=2&ved=0CCcQjBAwAg&url=http%3A%2F%2Fwww.txfa.org%2Fdocs%2FBallots-Debate.pdf&ei=llKwTvLrIJG5tge-iq39AQ&usg=AFQjCNF6Ga3QauN-uYKlDfaEnKtNhu6AXQ

**Comment by NickCarneiro** [comment]
This appears to be working.
