### ISSUE TITLE
Edit Judges

### ISSUE THREAD

**Issue by NickCarneiro** [NickCarneiro/Debate-Tab#46]
When you click on a judge it should bring up the form in a modal dialog with everything filled in. See the division code for an example.

**Comment by Ali-N** [comment]
Mostly done. Need to figure out how to check the division check boxes

**Comment by NickCarneiro** [comment]
$(".checkbox").attr("checked", false);

**Comment by NickCarneiro** [comment]
I was wrong about this. in jQuery 1.6 there is a better way:

$(".checkbox").prop("checked", false);

**Comment by NickCarneiro** [comment]
This looks good.
